# Generated by Django 4.1.7 on 2024-01-31 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0005_alter_customerreg1_bank_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow1',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_name', models.CharField(max_length=50)),
                ('para_1', models.CharField(max_length=50)),
                ('value_1', models.CharField(max_length=50)),
                ('para_2', models.CharField(max_length=50)),
                ('value_2', models.CharField(max_length=50)),
                ('para_3', models.CharField(max_length=50)),
                ('value_3', models.CharField(max_length=50)),
                ('para_4', models.CharField(blank=True, max_length=50, null=True)),
                ('value_4', models.CharField(blank=True, max_length=50, null=True)),
                ('para_5', models.CharField(blank=True, max_length=50, null=True)),
                ('value_5', models.CharField(blank=True, max_length=50, null=True)),
                ('Main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.applications')),
                ('User_names', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
