# Generated by Django 4.1.7 on 2024-02-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_remove_workflow1_main_model_workflow1_main_modell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow1',
            name='User_names',
        ),
        migrations.AddField(
            model_name='workflow1',
            name='User_names',
            field=models.JSONField(default=list),
        ),
    ]
