# Generated by Django 4.1.7 on 2024-02-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_remove_workflow1_user_names_workflow1_user_names'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workflow1',
            new_name='workflow',
        ),
    ]
