# Generated by Django 4.1.7 on 2024-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_rename_workflow1_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='Main_modell',
            new_name='AppID',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='application_name',
            new_name='AppName',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='application_id',
            new_name='WF_ID',
        ),
        migrations.AddField(
            model_name='workflow',
            name='Main_model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
