# Generated by Django 4.1.7 on 2024-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_rename_main_modell_workflow_appid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='para_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='value_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
