# Generated by Django 4.1.7 on 2024-02-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_workflow_para_3_alter_workflow_value_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLOG',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('WF_ID', models.CharField(max_length=70)),
                ('Doc_ID', models.CharField(max_length=70)),
                ('AppID', models.CharField(max_length=70)),
                ('AppName', models.CharField(max_length=70)),
                ('CurrentUser', models.CharField(max_length=70)),
                ('NextUser', models.CharField(max_length=70)),
                ('Action', models.CharField(max_length=70)),
                ('DateTimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
