# Generated by Django 4.1.7 on 2024-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_workflowlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlog',
            name='ProcessID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='ProcessName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
