# Generated by Django 4.1.7 on 2024-02-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_workflowlog_processid_workflowlog_processname'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='ProcessID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='ProcessName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
