# Generated by Django 4.1.7 on 2024-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_workflow_processid_workflow_processname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='AppID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='AppName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
