# Generated by Django 4.1.7 on 2024-02-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_alter_workflow_appid_alter_workflow_appname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='Main_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
