# Generated by Django 4.1.7 on 2024-02-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_applications_processname'),
        ('workflow', '0011_alter_workflow_main_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='ProcessID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='ProcessName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.processes'),
        ),
    ]
