# Generated by Django 4.1.7 on 2024-02-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_alter_workflow_processid_alter_workflow_processname'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlog',
            name='Comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
