# Generated by Django 4.1.7 on 2024-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='para_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='para_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='value_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='value_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
