# Generated by Django 4.1.7 on 2024-02-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_alter_workflow_para_1_alter_workflow_para_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInbox',
            fields=[
                ('inbox_id', models.AutoField(primary_key=True, serialize=False)),
                ('Doc_ID', models.CharField(max_length=70)),
                ('AppID', models.CharField(max_length=70)),
                ('ProcessID', models.IntegerField()),
                ('CurrentUser', models.CharField(max_length=70)),
                ('NextUser', models.CharField(max_length=70)),
                ('DateTimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
