# Generated by Django 4.1.7 on 2024-03-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_workflowinbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinbox',
            name='NextUser',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='NextUser',
            field=models.CharField(max_length=500),
        ),
    ]
